lsi: false
safe: true
source: .
destination: _site
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-remote-theme
  - jekyll-feed

baseurl: ""
url: https://avroots.nl

remote_theme: BDHU/minimalist
title: A.V. Roots
email: bestuur@avroots.nl
description: Oud A–Eskwadraaters kamer meubilair
color-scheme: light
logo: /assets/logo_vierkant.png
favicon: true

# Navigation links
header_pages:
  - index.md
  - activiteiten.md

collections:
  activiteiten:
    output: true