lsi: false
safe: true
source: .
destination: _site
theme: BDHU/minimalist
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: A.V. Roots
description: Alumni Vereniging Roots, de plek waar je jouw oud A-Eskwadraat kamergangers weer ontmoet!
color-scheme: light
logo: /assets/img/logo_vierkant.png