lsi: false
source: .
destination: _site
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-remote-theme
  - jekyll-feed

baseurl: ""
url: ""

remote_theme: BDHU/minimalist
title: A.V. Roots
email: bestuur@avroots.nl
description: A.V. Roots, voor oud A-Eskwadraaters!
color-scheme: light
logo: /assets/img/logo_vierkant.png
favicon: true

collections:
  activiteiten:
    output: true