name: nightly-build

on:
  schedule:
    # Runs at 03:30 UTC every day
    - cron: '30 3 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site
          future: false

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          name: github-pages
          retention-days: 1

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          preview: false
          artifact_name: github-pages